# Generated by Django 2.2.9 on 2021-02-27 05:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0002_auto_20210227_1501'),
    ]

    operations = [
        migrations.RenameField(
            model_name='group',
            old_name='tittle',
            new_name='description',
        ),
        migrations.AddField(
            model_name='group',
            name='slug',
            field=models.SlugField(default='', unique=True),
        ),
        migrations.AddField(
            model_name='group',
            name='title',
            field=models.CharField(default='TestGroup', max_length=200),
        ),
    ]
